config/routes.rb
Rails.application.routes.draw do
  resources :pruebas

  get 'informa/consulta'

  get 'informa/comentarios'

  devise_for :users
  get 'home/index'

end

app/models/prueba.rb
class Prueba < ActiveRecord::Base
end

app/models/tbitalarma.rb
class Tbitalarma < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/informa_controller.rb
class InformaController < ApplicationController
  def consulta
    @bitacora = Tbitalarma.where(:Id_Lay => params[:Id_Lay])
  end

  def comentarios
  end
end

app/controllers/pruebas_controller.rb
class PruebasController < ApplicationController
  before_action :set_prueba, only: [:show, :edit, :update, :destroy]

  # GET /pruebas
  # GET /pruebas.json
  def index
    @pruebas = Prueba.all
  end

  # GET /pruebas/1
  # GET /pruebas/1.json
  def show
  end

  # GET /pruebas/new
  def new
    @prueba = Prueba.new
  end

  # GET /pruebas/1/edit
  def edit
  end

  # POST /pruebas
  # POST /pruebas.json
  def create
    @prueba = Prueba.new(prueba_params)

    respond_to do |format|
      if @prueba.save
        format.html { redirect_to @prueba, notice: 'Prueba was successfully created.' }
        format.json { render :show, status: :created, location: @prueba }
      else
        format.html { render :new }
        format.json { render json: @prueba.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pruebas/1
  # PATCH/PUT /pruebas/1.json
  def update
    respond_to do |format|
      if @prueba.update(prueba_params)
        format.html { redirect_to @prueba, notice: 'Prueba was successfully updated.' }
        format.json { render :show, status: :ok, location: @prueba }
      else
        format.html { render :edit }
        format.json { render json: @prueba.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pruebas/1
  # DELETE /pruebas/1.json
  def destroy
    @prueba.destroy
    respond_to do |format|
      format.html { redirect_to pruebas_url, notice: 'Prueba was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prueba
      @prueba = Prueba.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prueba_params
      params.require(:prueba).permit(:texto, :fecha)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/informa_helper.rb
module InformaHelper
end

app/helpers/pruebas_helper.rb
module PruebasHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/informa/comentarios.html.erb
<h1>Informa#comentarios</h1>
<p>Find me in app/views/informa/comentarios.html.erb</p>

app/views/informa/consulta.html.erb
<table class="table table-responsive">
  <th>
    <tr>
      <td>Layout</td>
      <td>Formato</td>
      <td>Usuario</td>
      <td>Mensaje</td>
    </tr>
  </th>
  <tbody>
  <div>
    <% @bitacora.each do |datos| %>
        <tr>
          <td><%= datos.Id_Lay %></td>
          <td><%= datos.Id_Formato %></td>
          <td><%= datos.Id_Usuario %></td>
          <td><%= datos.mensaje %></td>
        </tr>
    <% end %>
  </div>

  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LogeNew</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="collapse navbar-collapse navbar-ex1-collapse">
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
        <li>
          <p class='navbar-text'>Bienvenido: <%= current_login.email %>.</p>
          <p class='navbar-text'><%= current_login.nom %>.</p>
        </li>
        <li>
          <p class='navbar-text'><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></p>
        </li>
    <% else %>
        <li><p class='navbar-text'><%= link_to "Crea una cuenta", new_user_registration_path %></p></li>

        <li><p class='navbar-text'><%= link_to "Logueate", new_user_session_path %></p></li>
    <% end %>
  </ul>
</div>

<%= yield %>

</body>
</html>

app/views/pruebas/_form.html.erb
<%= simple_form_for(@prueba) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :texto %>
    <%= f.input :fecha %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pruebas/edit.html.erb
<h1>Editing Prueba</h1>

<%= render 'form' %>

<%= link_to 'Show', @prueba %> |
<%= link_to 'Back', pruebas_path %>

app/views/pruebas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pruebas</h1>

<table>
  <thead>
    <tr>
      <th>Texto</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pruebas.each do |prueba| %>
      <tr>
        <td><%= prueba.texto %></td>
        <td><%= prueba.fecha %></td>
        <td><%= link_to 'Show', prueba %></td>
        <td><%= link_to 'Edit', edit_prueba_path(prueba) %></td>
        <td><%= link_to 'Destroy', prueba, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prueba', new_prueba_path %>

app/views/pruebas/new.html.erb
<h1>New Prueba</h1>

<%= render 'form' %>

<%= link_to 'Back', pruebas_path %>

app/views/pruebas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Texto:</strong>
  <%= @prueba.texto %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @prueba.fecha %>
</p>

<%= link_to 'Edit', edit_prueba_path(@prueba) %> |
<%= link_to 'Back', pruebas_path %>